import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';


// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
const PEOPLE = [
  {
    id: 0,
    name: 'Aria',
    sex: 'female'
  }, {
    id: 1,
    name: 'Logan',
    sex: 'male'
  }, {
    id: 2,
    name: 'Quinn',
    sex: 'female'
  }, {
    id: 3,
    name: 'Kai',
    sex: 'male'
  }, {
    id: 4,
    name: 'Dashiell',
    sex: 'male'
  }, {
    id: 5,
    name: 'John',
    sex: 'male'
  }, {
    id: 6,
    name: 'Seraphina',
    sex: 'female'
  }, {
    id: 7,
    name: 'Caroline',
    sex: 'female'
  }, {
    id: 8,
    name: 'Tobias',
    sex: 'male'
  }, {
    id: 9,
    name: 'Harper',
    sex: 'female'
  }, {
    id: 10,
    name: 'Mabe',
    sex: 'female'
  }, {
    id: 11,
    name: 'Iris',
    sex: 'female'
  }, {
    id: 12,
    name: 'Beatrice',
    sex: 'female'
  }, {
    id: 13,
    name: 'Knox',
    sex: 'male'
  }, {
    id: 14,
    name: 'August',
    sex: 'male'
  }, {
    id: 15,
    name: 'Poppy',
    sex: 'female'
  }, {
    id: 16,
    name: 'Aurora',
    sex: 'female'
  }, {
    id: 17,
    name: 'Wyatt',
    sex: 'male'
  }, {
    id: 18,
    name: 'Ezra',
    sex: 'male'
  }, {
    id: 19,
    name: 'Emily',
    sex: 'female'
  }, {
    id: 20,
    name: 'Sebastian',
    sex: 'male'
  }, {
    id: 21,
    name: 'Gabriel',
    sex: 'male'
  }, {
    id: 22,
    name: 'Charlie',
    sex: 'male'
  }, {
    id: 23,
    name: 'Isabella',
    sex: 'female'
  }, {
    id: 24,
    name: 'Elliot',
    sex: 'male'
  }, {
    id: 25,
    name: 'Declan',
    sex: 'male'
  }, {
    id: 26,
    name: 'Benjamin',
    sex: 'male'
  }, {
    id: 27,
    name: 'Gemma',
    sex: 'female'
  }, {
    id: 28,
    name: 'Lucas',
    sex: 'male'
  }, {
    id: 29,
    name: 'Chloe',
    sex: 'female'
  }, {
    id: 30,
    name: 'Khaleesi',
    sex: 'female'
  }, {
    id: 31,
    name: 'Austin',
    sex: 'male'
  }, {
    id: 32,
    name: 'Matilda',
    sex: 'female'
  }, {
    id: 33,
    name: 'Grayson',
    sex: 'male'
  }, {
    id: 34,
    name: 'Beckett',
    sex: 'male'
  }, {
    id: 35,
    name: 'Nicholas',
    sex: 'male'
  }, {
    id: 36,
    name: 'Ronan',
    sex: 'male'
  }, {
    id: 37,
    name: 'Eliza',
    sex: 'female'
  }, {
    id: 38,
    name: 'Imogen',
    sex: 'female'
  }, {
    id: 39,
    name: 'Amelia',
    sex: 'female'
  }, {
    id: 40,
    name: 'Nathaniel',
    sex: 'male'
  }, {
    id: 41,
    name: 'Ryker',
    sex: 'male'
  }, {
    id: 42,
    name: 'Olivia',
    sex: 'female'
  }, {
    id: 43,
    name: 'Leo',
    sex: 'male'
  }, {
    id: 44,
    name: 'Zane',
    sex: 'male'
  }, {
    id: 45,
    name: 'Grace',
    sex: 'female'
  }, {
    id: 46,
    name: 'Owen',
    sex: 'male'
  }, {
    id: 47,
    name: 'Clara',
    sex: 'female'
  }, {
    id: 48,
    name: 'Julian',
    sex: 'male'
  }, {
    id: 49,
    name: 'Caleb',
    sex: 'male'
  }, {
    id: 50,
    name: 'Nolan',
    sex: 'male'
  }, {
    id: 51,
    name: 'Roman',
    sex: 'male'
  }, {
    id: 52,
    name: 'Felix',
    sex: 'male'
  }, {
    id: 53,
    name: 'Aryan',
    sex: 'male'
  }, {
    id: 54,
    name: 'Lily',
    sex: 'female'
  }, {
    id: 55,
    name: 'Sloane',
    sex: 'female'
  }, {
    id: 56,
    name: 'Zoe',
    sex: 'female'
  }, {
    id: 57,
    name: 'Penelope',
    sex: 'female'
  }, {
    id: 58,
    name: 'Evangeline',
    sex: 'female'
  }, {
    id: 59,
    name: 'Julia',
    sex: 'female'
  }, {
    id: 60,
    name: 'Theo',
    sex: 'male'
  }, {
    id: 61,
    name: 'Nathan',
    sex: 'male'
  }, {
    id: 62,
    name: 'Juliet',
    sex: 'female'
  }, {
    id: 63,
    name: 'Josiah',
    sex: 'male'
  }, {
    id: 64,
    name: 'Harrison',
    sex: 'male'
  }, {
    id: 65,
    name: 'Archer',
    sex: 'male'
  }, {
    id: 66,
    name: 'Ellie',
    sex: 'female'
  }, {
    id: 67,
    name: 'Rowan',
    sex: 'male'
  }, {
    id: 68,
    name: 'Eden',
    sex: 'female'
  }, {
    id: 69,
    name: 'Rhys',
    sex: 'male'
  }, {
    id: 70,
    name: 'Evelyn',
    sex: 'female'
  }, {
    id: 71,
    name: 'Isabel',
    sex: 'female'
  }, {
    id: 72,
    name: 'Mae',
    sex: 'female'
  }, {
    id: 73,
    name: 'Mila',
    sex: 'female'
  }, {
    id: 74,
    name: 'Emmett',
    sex: 'male'
  }, {
    id: 75,
    name: 'Rose',
    sex: 'female'
  }, {
    id: 76,
    name: 'Axel',
    sex: 'male'
  }, {
    id: 77,
    name: 'Willow',
    sex: 'female'
  }, {
    id: 78,
    name: 'Cora',
    sex: 'female'
  }, {
    id: 79,
    name: 'David',
    sex: 'male'
  }, {
    id: 80,
    name: 'Miles',
    sex: 'male'
  }, {
    id: 81,
    name: 'Clementine',
    sex: 'female'
  }, {
    id: 82,
    name: 'Sophia',
    sex: 'female'
  }, {
    id: 83,
    name: 'Eloise',
    sex: 'female'
  }, {
    id: 84,
    name: 'Everly',
    sex: 'female'
  }, {
    id: 85,
    name: 'Maeve',
    sex: 'female'
  }, {
    id: 86,
    name: 'Nora',
    sex: 'female'
  }, {
    id: 87,
    name: 'Lucy',
    sex: 'female'
  }, {
    id: 88,
    name: 'Adeline',
    sex: 'female'
  }, {
    id: 89,
    name: 'Hazel',
    sex: 'female'
  }, {
    id: 90,
    name: 'Oscar',
    sex: 'male'
  }, {
    id: 91,
    name: 'Ruby',
    sex: 'female'
  }, {
    id: 92,
    name: 'Silas',
    sex: 'male'
  }, {
    id: 93,
    name: 'Mia',
    sex: 'female'
  }, {
    id: 94,
    name: 'Jude',
    sex: 'male'
  }, {
    id: 95,
    name: 'Evie',
    sex: 'female'
  }, {
    id: 96,
    name: 'Luna',
    sex: 'female'
  }, {
    id: 97,
    name: 'Wren',
    sex: 'female'
  }, {
    id: 98,
    name: 'Hadley',
    sex: 'female'
  }, {
    id: 99,
    name: 'Ivy',
    sex: 'female'
  }, {
    id: 100,
    name: 'Lachlan',
    sex: 'male'
  }, {
    id: 101,
    name: 'Emmeline',
    sex: 'female'
  }, {
    id: 102,
    name: 'Hugo',
    sex: 'male'
  }, {
    id: 103,
    name: 'Stella',
    sex: 'female'
  }, {
    id: 104,
    name: 'Maddox',
    sex: 'male'
  }, {
    id: 105,
    name: 'Asher',
    sex: 'male'
  }, {
    id: 106,
    name: 'Jayden',
    sex: 'male'
  }, {
    id: 107,
    name: 'Daisy',
    sex: 'female'
  }, {
    id: 108,
    name: 'Callum',
    sex: 'male'
  }, {
    id: 109,
    name: 'Jasper',
    sex: 'male'
  }, {
    id: 110,
    name: 'Emma',
    sex: 'female'
  }, {
    id: 111,
    name: 'Claire',
    sex: 'female'
  }, {
    id: 112,
    name: 'Lola',
    sex: 'female'
  }, {
    id: 113,
    name: 'Jonah',
    sex: 'male'
  }, {
    id: 114,
    name: 'Sienna',
    sex: 'female'
  }, {
    id: 115,
    name: 'Ada',
    sex: 'female'
  }, {
    id: 116,
    name: 'Scarlett',
    sex: 'female'
  }, {
    id: 117,
    name: 'Sawyer',
    sex: 'male'
  }, {
    id: 118,
    name: 'Hannah',
    sex: 'female'
  }, {
    id: 119,
    name: 'Soren',
    sex: 'male'
  }, {
    id: 120,
    name: 'Maya',
    sex: 'female'
  }, {
    id: 121,
    name: 'Arabella',
    sex: 'female'
  }, {
    id: 122,
    name: 'Beau',
    sex: 'male'
  }, {
    id: 123,
    name: 'Maxwell',
    sex: 'male'
  }, {
    id: 124,
    name: 'Anna',
    sex: 'female'
  }, {
    id: 125,
    name: 'Lila',
    sex: 'female'
  }, {
    id: 126,
    name: 'Sadie',
    sex: 'female'
  }, {
    id: 127,
    name: 'James',
    sex: 'male'
  }, {
    id: 128,
    name: 'Arthur',
    sex: 'male'
  }, {
    id: 129,
    name: 'Aurelia',
    sex: 'female'
  }, {
    id: 130,
    name: 'Samuel',
    sex: 'male'
  }, {
    id: 131,
    name: 'Atticus',
    sex: 'male'
  }, {
    id: 132,
    name: 'Bodhi',
    sex: 'male'
  }, {
    id: 133,
    name: 'Elijah',
    sex: 'male'
  }, {
    id: 134,
    name: 'Griffin',
    sex: 'male'
  }, {
    id: 135,
    name: 'Graham',
    sex: 'male'
  }, {
    id: 136,
    name: 'Weston',
    sex: 'male'
  }, {
    id: 137,
    name: 'Hudson',
    sex: 'male'
  }, {
    id: 138,
    name: 'Henry',
    sex: 'male'
  }, {
    id: 139,
    name: 'Levi',
    sex: 'male'
  }, {
    id: 140,
    name: 'Nova',
    sex: 'female'
  }, {
    id: 141,
    name: 'Margaret',
    sex: 'female'
  }, {
    id: 142,
    name: 'Adelaide',
    sex: 'female'
  }, {
    id: 143,
    name: 'Audrey',
    sex: 'female'
  }, {
    id: 144,
    name: 'Jane',
    sex: 'female'
  }, {
    id: 145,
    name: 'Alice',
    sex: 'female'
  }, {
    id: 146,
    name: 'Simon',
    sex: 'male'
  }, {
    id: 147,
    name: 'Ella',
    sex: 'female'
  }, {
    id: 148,
    name: 'Violet',
    sex: 'female'
  }, {
    id: 149,
    name: 'Thomas',
    sex: 'male'
  }, {
    id: 150,
    name: 'Madeline',
    sex: 'female'
  }, {
    id: 151,
    name: 'Genevieve',
    sex: 'female'
  }, {
    id: 152,
    name: 'Oliver',
    sex: 'male'
  }, {
    id: 153,
    name: 'Lydia',
    sex: 'female'
  }, {
    id: 154,
    name: 'Ethan',
    sex: 'male'
  }, {
    id: 155,
    name: 'Liam',
    sex: 'male'
  }, {
    id: 156,
    name: 'Alexander',
    sex: 'male'
  }, {
    id: 157,
    name: 'Wesley',
    sex: 'male'
  }, {
    id: 158,
    name: 'William',
    sex: 'male'
  }, {
    id: 159,
    name: 'Harlow',
    sex: 'female'
  }, {
    id: 160,
    name: 'Isaac',
    sex: 'male'
  }, {
    id: 161,
    name: 'Eliana',
    sex: 'female'
  }, {
    id: 162,
    name: 'Esme',
    sex: 'female'
  }, {
    id: 163,
    name: 'Elizabeth',
    sex: 'female'
  }, {
    id: 164,
    name: 'Xavier',
    sex: 'male'
  }, {
    id: 165,
    name: 'Piper',
    sex: 'female'
  }, {
    id: 166,
    name: 'Andrew',
    sex: 'male'
  }, {
    id: 167,
    name: 'Abigail',
    sex: 'female'
  }, {
    id: 168,
    name: 'Olive',
    sex: 'female'
  }, {
    id: 169,
    name: 'Everett',
    sex: 'male'
  }, {
    id: 170,
    name: 'Lincoln',
    sex: 'male'
  }, {
    id: 171,
    name: 'Eli',
    sex: 'male'
  }, {
    id: 172,
    name: 'Elodie',
    sex: 'female'
  }, {
    id: 173,
    name: 'Josephine',
    sex: 'female'
  }, {
    id: 174,
    name: 'Thea',
    sex: 'female'
  }, {
    id: 175,
    name: 'Emilia',
    sex: 'female'
  }, {
    id: 176,
    name: 'Florence',
    sex: 'female'
  }, {
    id: 177,
    name: 'Ava',
    sex: 'female'
  }, {
    id: 178,
    name: 'Isla',
    sex: 'female'
  }, {
    id: 179,
    name: 'Willa',
    sex: 'female'
  }, {
    id: 180,
    name: 'Milo',
    sex: 'male'
  }, {
    id: 181,
    name: 'Charlotte',
    sex: 'female'
  }, {
    id: 182,
    name: 'Noah',
    sex: 'male'
  }, {
    id: 183,
    name: 'Matthew',
    sex: 'male'
  }, {
    id: 184,
    name: 'Luca',
    sex: 'male'
  }, {
    id: 185,
    name: 'Finn',
    sex: 'male'
  }, {
    id: 186,
    name: 'Cordelia',
    sex: 'female'
  }, {
    id: 187,
    name: 'Theodore',
    sex: 'male'
  }, {
    id: 188,
    name: 'George',
    sex: 'male'
  }, {
    id: 189,
    name: 'Jackson',
    sex: 'male'
  }, {
    id: 190,
    name: 'Jacob',
    sex: 'male'
  }, {
    id: 191,
    name: 'Eleanor',
    sex: 'female'
  }, {
    id: 192,
    name: 'Daniel',
    sex: 'male'
  }, {
    id: 193,
    name: 'Ryder',
    sex: 'male'
  }, {
    id: 194,
    name: 'Annabelle',
    sex: 'female'
  }, {
    id: 195,
    name: 'Zachary',
    sex: 'male'
  }, {
    id: 196,
    name: 'Luke',
    sex: 'male'
  }, {
    id: 197,
    name: 'Jack',
    sex: 'male'
  }, {
    id: 198,
    name: 'Charles',
    sex: 'male'
  }, {
    id: 199,
    name: 'Bennett',
    sex: 'male'
  }
]
ReactDOM.render(
  <React.StrictMode>
    <App data={PEOPLE} />
  </React.StrictMode>,
  document.getElementById('root')
);
